CREATE ROLE "finARM_users" NOSUPERUSER INHERIT NOCREATEDB CREATEROLE NOREPLICATION;
GRANT CONNECT, TEMPORARY ON DATABASE "finARM" TO GROUP "armDirectors";
GRANT CONNECT, TEMPORARY ON DATABASE "finARM" TO GROUP "finARM_users";
REVOKE ALL ON DATABASE "finARM" FROM public;
