CREATE ROLE "armDirectors"
  NOSUPERUSER INHERIT NOCREATEDB CREATEROLE;
  
CREATE ROLE "armUsers"
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;
  
ALTER DEFAULT PRIVILEGES 
    GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES
    TO postgres;

ALTER DEFAULT PRIVILEGES 
    GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES
    TO "armDirectors";

ALTER DEFAULT PRIVILEGES 
    GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES
    TO "armUsers";  